# Generated by Django 4.2.11 on 2026-07-12 23:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('schema_name', models.CharField(max_length=63)),
                ('owner_id', models.UUIDField(blank=True, help_text='UUID do administrador da associação (schema do tenant)', null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('on_trial', models.BooleanField(default=True)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/%Y/%m/')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Associação',
                'verbose_name_plural': 'Associações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
    ]
