# Generated by Django 4.2.11 on 2026-07-12 23:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='CPF inválido. Use formato XXX.XXX.XXX-XX ou 11 dígitos.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$|^\\d{11}$')])),
                ('cnpj', models.CharField(blank=True, help_text='Para instituições filiadas', max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='CNPJ inválido.', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$|^\\d{14}$')])),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=255, null=True)),
                ('area_atuacao', models.CharField(blank=True, max_length=255, null=True)),
                ('lattes_url', models.URLField(blank=True, null=True)),
                ('orcid', models.CharField(blank=True, max_length=19, null=True)),
                ('consentimento_lgpd', models.BooleanField(default=False)),
                ('consentimento_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome_completo'],
                'indexes': [models.Index(fields=['cpf'], name='membros_mem_cpf_ef4b0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Filiacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('efetivo', 'Efetivo'), ('estudante', 'Estudante'), ('honorario', 'Honorário'), ('institucional', 'Institucional')], default='efetivo', max_length=20)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inadimplente', 'Inadimplente'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada'), ('honoraria', 'Honorária')], db_index=True, default='ativa', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('mandato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiacoes', to='mandatos.mandato')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiacoes', to='membros.membro')),
            ],
            options={
                'verbose_name': 'Filiação',
                'verbose_name_plural': 'Filiações',
            },
        ),
        migrations.CreateModel(
            name='Anuidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ano_referencia', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('isenta', 'Isenta'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('nf_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('filiacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuidades', to='membros.filiacao')),
            ],
            options={
                'verbose_name': 'Anuidade',
                'verbose_name_plural': 'Anuidades',
            },
        ),
        migrations.AddIndex(
            model_name='filiacao',
            index=models.Index(fields=['membro', 'status'], name='membros_fil_membro__582d8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='anuidade',
            unique_together={('filiacao', 'ano_referencia')},
        ),
    ]
