# Generated by Django 4.2.11 on 2026-07-15 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuário do sistema vinculado a este associado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membro_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
