# Generated by Django 4.2.11 on 2026-07-12 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mandatos', '0001_initial'),
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallForPapers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('instrucoes', models.TextField()),
                ('data_abertura', models.DateTimeField()),
                ('data_fechamento', models.DateTimeField()),
                ('areas_tematicas', models.JSONField(blank=True, default=list)),
                ('max_submissoes_por_autor', models.PositiveSmallIntegerField(default=2)),
                ('anonimo', models.BooleanField(default=True, help_text='Parecer duplo-cego')),
            ],
            options={
                'verbose_name': 'Call for Papers',
                'verbose_name_plural': 'Calls for Papers',
            },
        ),
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], default='presencial', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('inscricoes_abertas', 'Inscrições Abertas'), ('cfp_aberto', 'Call for Papers Aberto'), ('em_avaliacao', 'Em Avaliação'), ('encerrado', 'Encerrado'), ('anais_publicados', 'Anais Publicados'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=25)),
                ('capacidade_max', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_inscricao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='mandatos.mandato')),
            ],
            options={
                'verbose_name': 'Evento Acadêmico',
                'verbose_name_plural': 'Eventos Acadêmicos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SubmissaoTrabalho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('resumo', models.TextField()),
                ('palavras_chave', models.JSONField(blank=True, default=list)),
                ('area_tematica', models.CharField(blank=True, max_length=100, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='eventos/submissoes/%Y/%m/')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetido', 'Submetido'), ('em_parecer', 'Em Parecer'), ('aceito', 'Aceito'), ('aceito_com_revisoes', 'Aceito com Revisões'), ('rejeitado', 'Rejeitado'), ('retirado', 'Retirado')], default='rascunho', max_length=25)),
                ('submetido_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to=settings.AUTH_USER_MODEL)),
                ('cfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='eventos.callforpapers')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissoes', to='membros.membro')),
            ],
            options={
                'verbose_name': 'Submissão de Trabalho',
                'verbose_name_plural': 'Submissões de Trabalhos',
            },
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recomendacao', models.CharField(blank=True, choices=[('aceitar', 'Aceitar'), ('aceitar_com_revisoes', 'Aceitar com Revisões'), ('rejeitar', 'Rejeitar')], max_length=25, null=True)),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comentarios_autor', models.TextField(blank=True, null=True)),
                ('comentarios_internos', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('parecerista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to=settings.AUTH_USER_MODEL)),
                ('submissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='eventos.submissaotrabalho')),
            ],
            options={
                'verbose_name': 'Parecer',
                'verbose_name_plural': 'Pareceres',
            },
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('confirmada', models.BooleanField(default=False)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='eventos/certificados/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.eventoacademico')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_evento', to='membros.membro')),
            ],
            options={
                'verbose_name': 'Inscrição em Evento',
                'verbose_name_plural': 'Inscrições em Eventos',
            },
        ),
        migrations.AddField(
            model_name='callforpapers',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_for_papers', to='eventos.eventoacademico'),
        ),
        migrations.CreateModel(
            name='AnaisPublicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('issn', models.CharField(blank=True, max_length=20, null=True)),
                ('doi_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('url_publicacao', models.URLField(blank=True, null=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anais', to='eventos.eventoacademico')),
            ],
            options={
                'verbose_name': 'Publicação de Anais',
                'verbose_name_plural': 'Publicações de Anais',
            },
        ),
        migrations.AddIndex(
            model_name='submissaotrabalho',
            index=models.Index(fields=['cfp', 'status'], name='eventos_sub_cfp_id_0299d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parecer',
            unique_together={('submissao', 'parecerista')},
        ),
        migrations.AddIndex(
            model_name='inscricaoevento',
            index=models.Index(fields=['evento', 'confirmada'], name='eventos_ins_evento__994ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoacademico',
            index=models.Index(fields=['status', 'data_inicio'], name='eventos_eve_status_1ce4f2_idx'),
        ),
    ]
