# Generated by Django 4.2.11 on 2026-07-12 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoMandato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cargo', models.CharField(choices=[('presidente', 'Presidente'), ('vice_presidente', 'Vice-Presidente'), ('secretario', 'Secretário'), ('secretario_adjunto', 'Secretário Adjunto'), ('tesoureiro', 'Tesoureiro'), ('tesoureiro_adjunto', 'Tesoureiro Adjunto'), ('diretor', 'Diretor'), ('conselho_fiscal', 'Conselho Fiscal'), ('outro', 'Outro')], max_length=30)),
                ('cargo_custom', models.CharField(blank=True, help_text='Nome do cargo quando tipo = outro', max_length=100, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo no Mandato',
                'verbose_name_plural': 'Cargos no Mandato',
            },
        ),
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ex: Diretoria 2024-2026', max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('ativo', 'Ativo'), ('transicao', 'Em Transição'), ('encerrado', 'Encerrado'), ('arquivado', 'Arquivado')], db_index=True, default='planejado', max_length=20)),
                ('numero_sequencial', models.PositiveIntegerField(help_text='Número sequencial do mandato na associação (1, 2, 3...)')),
                ('observacoes_encerramento', models.TextField(blank=True, null=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mandato',
                'verbose_name_plural': 'Mandatos',
                'ordering': ['-numero_sequencial'],
            },
        ),
        migrations.CreateModel(
            name='TransicaoMandato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('onboarding_parcial', 'Onboarding Parcial'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=25)),
                ('data_inicio_transicao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('progresso_percentual', models.PositiveSmallIntegerField(default=0)),
                ('notas_transicao', models.TextField(blank=True, null=True)),
                ('mandato_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicao_como_anterior', to='mandatos.mandato')),
                ('mandato_novo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicao_como_novo', to='mandatos.mandato')),
            ],
            options={
                'verbose_name': 'Transição de Mandato',
                'verbose_name_plural': 'Transições de Mandato',
            },
        ),
        migrations.CreateModel(
            name='OnboardingEtapa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('obrigatoria', models.BooleanField(default=True)),
                ('concluida', models.BooleanField(default=False)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('dados_contexto', models.JSONField(blank=True, null=True)),
                ('perfil_minimo', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_etapas', to=settings.AUTH_USER_MODEL)),
                ('transicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_onboarding', to='mandatos.transicaomandato')),
            ],
            options={
                'verbose_name': 'Etapa de Onboarding',
                'verbose_name_plural': 'Etapas de Onboarding',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='MandatoSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='encerramento | transicao | manual', max_length=20)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('dados', models.JSONField()),
                ('hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_criados', to=settings.AUTH_USER_MODEL)),
                ('mandato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='mandatos.mandato')),
            ],
            options={
                'verbose_name': 'Snapshot de Mandato',
                'verbose_name_plural': 'Snapshots de Mandato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mandato',
            index=models.Index(fields=['status'], name='mandatos_ma_status_68c070_idx'),
        ),
        migrations.AddIndex(
            model_name='mandato',
            index=models.Index(fields=['data_inicio', 'data_fim'], name='mandatos_ma_data_in_26bb8f_idx'),
        ),
        migrations.AddField(
            model_name='cargomandato',
            name='mandato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='mandatos.mandato'),
        ),
        migrations.AddField(
            model_name='cargomandato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_mandato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='transicaomandato',
            unique_together={('mandato_anterior', 'mandato_novo')},
        ),
        migrations.AddIndex(
            model_name='onboardingetapa',
            index=models.Index(fields=['transicao', 'ordem'], name='mandatos_on_transic_3b844e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingetapa',
            unique_together={('transicao', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='mandatosnapshot',
            index=models.Index(fields=['mandato', 'tipo'], name='mandatos_ma_mandato_3f44fc_idx'),
        ),
        migrations.AddIndex(
            model_name='cargomandato',
            index=models.Index(fields=['mandato', 'ativo'], name='mandatos_ca_mandato_af471e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cargomandato',
            unique_together={('mandato', 'usuario', 'cargo')},
        ),
    ]
