# Generated by Django 4.2.11 on 2026-07-12 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mandatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineInstitucional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('contexto_id', models.UUIDField(blank=True, null=True)),
                ('mandato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='mandatos.mandato')),
            ],
            options={
                'verbose_name': 'Evento na Timeline',
                'verbose_name_plural': 'Timeline Institucional',
                'ordering': ['-data_evento'],
                'indexes': [models.Index(fields=['mandato', 'data_evento'], name='memoria_tim_mandato_11b0e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContextoHistorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('decisao', 'Decisão'), ('processo', 'Processo'), ('evento', 'Evento'), ('financeiro', 'Financeiro'), ('comunicacao', 'Comunicação'), ('filiacao', 'Filiação'), ('evento_academico', 'Evento Acadêmico'), ('outro', 'Outro')], max_length=25)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('decisao', models.CharField(blank=True, help_text='O que foi decidido', max_length=500, null=True)),
                ('motivo', models.TextField(blank=True, help_text='Por que foi decidido — essencial para H1', null=True)),
                ('entidade_tipo', models.CharField(blank=True, help_text='Tipo da entidade vinculada: membro, evento, etc.', max_length=50, null=True)),
                ('entidade_id', models.UUIDField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('visivel_diretoria', models.BooleanField(default=True)),
                ('arquivado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextos_autor', to=settings.AUTH_USER_MODEL)),
                ('mandato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextos', to='mandatos.mandato')),
            ],
            options={
                'verbose_name': 'Contexto Histórico',
                'verbose_name_plural': 'Contextos Históricos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mandato', 'tipo'], name='memoria_con_mandato_c3b403_idx'), models.Index(fields=['entidade_tipo', 'entidade_id'], name='memoria_con_entidad_907295_idx')],
            },
        ),
    ]
